local_base_dir: "C:/Overrides/"
department_name: "BT2"


sftp_hosts:
  - hostname: "AFV"
    ip_address: "10.243.13.85"
    resources:
      - "Insp"
      - "House"
      - "UitSeq"
    db_path: "//SVKWA337/Pilot_Project/Rxi/AFV/controller.ctrl/controller_l.mdb"

  - hostname: "REG"
    ip_address: "10.243.13.89"
    resources:
      - "House"
    db_path: "//SVKWA337/Pilot_Project/Rxi/AFV/controller.ctrl/controller_l.mdb"
